### ISSUE TITLE
label

### ISSUE THREAD

**Issue by Popukar0421** [BioDataLearning/TDm6A#1]

**Comment by Zhaoshihao0421** [comment]
> 请问你的test数据集例如HEK293的label中【1，0】是负还是正啊。
> 我看论文中说的是正负1：10
> 一般不是【1，0】是正样本吗

**Comment by Zhaoshihao0421** [comment]
> 请问你的test数据集例如HEK293的label中【1，0】是负还是正啊。
> 我看论文中说的是正负1：10
> 一般不是【1，0】是正样本吗

**Comment by Zhaoshihao0421** [comment]
> _No description provided._
